apiVersion: v1
data: {}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: openshift-monitoring
  name: kube-rbac-proxy
  namespace: openshift-monitoring
stringData:
  config.yaml: |-
    "authorization":
      "static":
      - "resourceRequest": false
        "user":
          "name": "system:serviceaccount:openshift-monitoring:prometheus-k8s"
type: Opaque
